import { WeatherForecastResponse } from "../models/weather.model";

export const mockedResponse: WeatherForecastResponse = {
  '@context': [
    'https://geojson.org/geojson-ld/geojson-context.jsonld',
    {
      '@version': '1.1',
      wx: 'https://api.weather.gov/ontology#',
      geo: 'http://www.opengis.net/ont/geosparql#',
      unit: 'http://codes.wmo.int/common/unit/',
      '@vocab': 'https://api.weather.gov/ontology#',
    },
  ],
  type: 'Feature',
  geometry: {
    type: 'Polygon',
    coordinates: [
      [
        [-97.137207, 39.7444372],
        [-97.1367549, 39.7223799],
        [-97.1080809, 39.7227252],
        [-97.10852700000001, 39.7447825],
        [-97.137207, 39.7444372],
      ],
    ],
  },
  properties: {
    updated: '2024-03-30T15:26:40+00:00',
    units: 'us',
    forecastGenerator: 'BaselineForecastGenerator',
    generatedAt: '2024-03-30T17:18:59+00:00',
    updateTime: '2024-03-30T15:26:40+00:00',
    validTimes: '2024-03-30T09:00:00+00:00/P7DT16H',
    elevation: {
      unitCode: 'wmoUnit:m',
      value: 456.8952,
    },
    periods: [
      {
        number: 1,
        name: 'This Afternoon',
        startTime: '2024-03-30T12:00:00-05:00',
        endTime: '2024-03-30T18:00:00-05:00',
        isDaytime: true,
        temperature: 62,
        temperatureUnit: 'F',
        temperatureTrend: null,
        probabilityOfPrecipitation: {
          unitCode: 'wmoUnit:percent',
          value: null,
        },
        dewpoint: {
          unitCode: 'wmoUnit:degC',
          value: 1.1111111111111112,
        },
        relativeHumidity: {
          unitCode: 'wmoUnit:percent',
          value: 54,
        },
        windSpeed: '5 to 15 mph',
        windDirection: 'NE',
        icon: 'https://api.weather.gov/icons/land/day/sct?size=medium',
        shortForecast: 'Mostly Sunny',
         detailedForecast:
          'Mostly sunny, with a high near 62. Northeast wind 5 to 15 mph, with gusts as high as 20 mph.',
      },
      {
        number: 2,
        name: 'Tonight',
        startTime: '2024-03-30T18:00:00-05:00',
        endTime: '2024-03-31T06:00:00-05:00',
        isDaytime: false,
        temperature: 43,
        temperatureUnit: 'F',
        temperatureTrend: null,
        probabilityOfPrecipitation: {
          unitCode: 'wmoUnit:percent',
          value: null,
        },
        dewpoint: {
          unitCode: 'wmoUnit:degC',
          value: 3.888888888888889,
        },
        relativeHumidity: {
          unitCode: 'wmoUnit:percent',
          value: 79,
        },
        windSpeed: '5 to 10 mph',
        windDirection: 'E',
        icon: 'https://api.weather.gov/icons/land/night/sct?size=medium',
        shortForecast: 'Partly Cloudy',
        detailedForecast:
          'Partly cloudy, with a low around 43. East wind 5 to 10 mph.',
      },
      {
        number: 3,
        name: 'Sunday',
        startTime: '2024-03-31T06:00:00-05:00',
        endTime: '2024-03-31T18:00:00-05:00',
        isDaytime: true,
        temperature: 68,
        temperatureUnit: 'F',
        temperatureTrend: null,
        probabilityOfPrecipitation: {
          unitCode: 'wmoUnit:percent',
          value: null,
        },
        dewpoint: {
          unitCode: 'wmoUnit:degC',
          value: 10.555555555555555,
        },
        relativeHumidity: {
          unitCode: 'wmoUnit:percent',
          value: 100,
        },
        windSpeed: '5 to 10 mph',
        windDirection: 'NE',
        icon: 'https://api.weather.gov/icons/land/day/bkn?size=medium',
        shortForecast: 'Partly Sunny',
        detailedForecast:
          'Partly sunny, with a high near 68. Northeast wind 5 to 10 mph.',
      },
      {
        number: 4,
        name: 'Sunday Night',
        startTime: '2024-03-31T18:00:00-05:00',
        endTime: '2024-04-01T06:00:00-05:00',
        isDaytime: false,
        temperature: 44,
        temperatureUnit: 'F',
        temperatureTrend: null,
        probabilityOfPrecipitation: {
          unitCode: 'wmoUnit:percent',
          value: 30,
        },
        dewpoint: {
          unitCode: 'wmoUnit:degC',
          value: 8.88888888888889,
        },
        relativeHumidity: {
          unitCode: 'wmoUnit:percent',
          value: 96,
        },
        windSpeed: '10 to 15 mph',
        windDirection: 'NE',
        icon: 'https://api.weather.gov/icons/land/night/rain_showers,20/tsra_sct,30?size=medium',
        shortForecast: 'Chance Showers And Thunderstorms',
        detailedForecast:
          'A slight chance of rain showers between 7pm and 1am, then a chance of showers and thunderstorms. Mostly cloudy, with a low around 44. Northeast wind 10 to 15 mph, with gusts as high as 20 mph. Chance of precipitation is 30%.',
      },
      {
        number: 5,
        name: 'Monday',
        startTime: '2024-04-01T06:00:00-05:00',
        endTime: '2024-04-01T18:00:00-05:00',
        isDaytime: true,
        temperature: 55,
        temperatureUnit: 'F',
        temperatureTrend: null,
        probabilityOfPrecipitation: {
          unitCode: 'wmoUnit:percent',
          value: 30,
        },
        dewpoint: {
          unitCode: 'wmoUnit:degC',
          value: 6.666666666666667,
        },
        relativeHumidity: {
          unitCode: 'wmoUnit:percent',
          value: 100,
        },
        windSpeed: '15 to 20 mph',
        windDirection: 'N',
        icon: 'https://api.weather.gov/icons/land/day/tsra_sct,30?size=medium',
        shortForecast: 'Chance Showers And Thunderstorms',
        detailedForecast:
          'A chance of rain showers before 7am, then a chance of showers and thunderstorms. Partly sunny, with a high near 55. North wind 15 to 20 mph, with gusts as high as 30 mph. Chance of precipitation is 30%.',
      },
      {
        number: 6,
        name: 'Monday Night',
        startTime: '2024-04-01T18:00:00-05:00',
        endTime: '2024-04-02T06:00:00-05:00',
        isDaytime: false,
        temperature: 33,
        temperatureUnit: 'F',
        temperatureTrend: null,
        probabilityOfPrecipitation: {
          unitCode: 'wmoUnit:percent',
          value: 40,
        },
        dewpoint: {
          unitCode: 'wmoUnit:degC',
          value: 3.888888888888889,
        },
        relativeHumidity: {
          unitCode: 'wmoUnit:percent',
          value: 96,
        },
        windSpeed: '20 to 25 mph',
        windDirection: 'N',
        icon: 'https://api.weather.gov/icons/land/night/rain_showers,40/rain,40?size=medium',
        shortForecast: 'Chance Rain Showers then Chance Light Rain',
        detailedForecast:
          'A chance of rain showers before 1am, then a chance of rain. Mostly cloudy, with a low around 33. North wind 20 to 25 mph, with gusts as high as 40 mph. Chance of precipitation is 40%.',
      },
      {
        number: 7,
        name: 'Tuesday',
        startTime: '2024-04-02T06:00:00-05:00',
        endTime: '2024-04-02T18:00:00-05:00',
        isDaytime: true,
        temperature: 54,
        temperatureUnit: 'F',
        temperatureTrend: null,
        probabilityOfPrecipitation: {
          unitCode: 'wmoUnit:percent',
          value: 40,
        },
        dewpoint: {
          unitCode: 'wmoUnit:degC',
          value: 0,
        },
        relativeHumidity: {
          unitCode: 'wmoUnit:percent',
          value: 92,
        },
        windSpeed: '20 to 25 mph',
        windDirection: 'N',
        icon: 'https://api.weather.gov/icons/land/day/rain,40/wind_sct?size=medium',
        shortForecast: 'Chance Light Rain then Mostly Sunny',
        detailedForecast:
          'A chance of rain before 7am. Mostly sunny, with a high near 54. North wind 20 to 25 mph, with gusts as high as 40 mph. Chance of precipitation is 40%.',
      },
      {
        number: 8,
        name: 'Tuesday Night',
        startTime: '2024-04-02T18:00:00-05:00',
        endTime: '2024-04-03T06:00:00-05:00',
        isDaytime: false,
        temperature: 32,
        temperatureUnit: 'F',
        temperatureTrend: null,
        probabilityOfPrecipitation: {
          unitCode: 'wmoUnit:percent',
          value: null,
        },
        dewpoint: {
          unitCode: 'wmoUnit:degC',
          value: -2.7777777777777777,
        },
        relativeHumidity: {
          unitCode: 'wmoUnit:percent',
          value: 75,
        },
        windSpeed: '15 to 20 mph',
        windDirection: 'NW',
        icon: 'https://api.weather.gov/icons/land/night/few?size=medium',
        shortForecast: 'Mostly Clear',
        detailedForecast:
          'Mostly clear, with a low around 32. Northwest wind 15 to 20 mph, with gusts as high as 30 mph.',
      },
      {
        number: 9,
        name: 'Wednesday',
        startTime: '2024-04-03T06:00:00-05:00',
        endTime: '2024-04-03T18:00:00-05:00',
        isDaytime: true,
        temperature: 60,
        temperatureUnit: 'F',
        temperatureTrend: null,
        probabilityOfPrecipitation: {
          unitCode: 'wmoUnit:percent',
          value: null,
        },
        dewpoint: {
          unitCode: 'wmoUnit:degC',
          value: -1.1111111111111112,
        },
        relativeHumidity: {
          unitCode: 'wmoUnit:percent',
          value: 81,
        },
        windSpeed: '10 to 15 mph',
        windDirection: 'NW',
        icon: 'https://api.weather.gov/icons/land/day/skc?size=medium',
        shortForecast: 'Sunny',
        detailedForecast:
          'Sunny, with a high near 60. Northwest wind 10 to 15 mph, with gusts as high as 25 mph.',
      },
      {
        number: 10,
        name: 'Wednesday Night',
        startTime: '2024-04-03T18:00:00-05:00',
        endTime: '2024-04-04T06:00:00-05:00',
        isDaytime: false,
        temperature: 33,
        temperatureUnit: 'F',
        temperatureTrend: null,
        probabilityOfPrecipitation: {
          unitCode: 'wmoUnit:percent',
          value: null,
        },
        dewpoint: {
          unitCode: 'wmoUnit:degC',
          value: -1.6666666666666667,
        },
        relativeHumidity: {
          unitCode: 'wmoUnit:percent',
          value: 78,
        },
        windSpeed: '10 to 15 mph',
        windDirection: 'E',
        icon: 'https://api.weather.gov/icons/land/night/skc?size=medium',
        shortForecast: 'Clear',
        detailedForecast: 'Clear, with a low around 33.',
      },
      {
        number: 11,
        name: 'Thursday',
        startTime: '2024-04-04T06:00:00-05:00',
        endTime: '2024-04-04T18:00:00-05:00',
        isDaytime: true,
        temperature: 67,
        temperatureUnit: 'F',
        temperatureTrend: null,
        probabilityOfPrecipitation: {
          unitCode: 'wmoUnit:percent',
          value: null,
        },
        dewpoint: {
          unitCode: 'wmoUnit:degC',
          value: 0.5555555555555556,
        },
        relativeHumidity: {
          unitCode: 'wmoUnit:percent',
          value: 85,
        },
        windSpeed: '5 to 15 mph',
        windDirection: 'S',
        icon: 'https://api.weather.gov/icons/land/day/skc?size=medium',
        shortForecast: 'Sunny',
        detailedForecast: 'Sunny, with a high near 67.',
      },
      {
        number: 12,
        name: 'Thursday Night',
        startTime: '2024-04-04T18:00:00-05:00',
        endTime: '2024-04-05T06:00:00-05:00',
        isDaytime: false,
        temperature: 40,
        temperatureUnit: 'F',
        temperatureTrend: null,
        probabilityOfPrecipitation: {
          unitCode: 'wmoUnit:percent',
          value: null,
        },
        dewpoint: {
          unitCode: 'wmoUnit:degC',
          value: 0.5555555555555556,
        },
        relativeHumidity: {
          unitCode: 'wmoUnit:percent',
          value: 70,
        },
        windSpeed: '10 to 15 mph',
        windDirection: 'SE',
        icon: 'https://api.weather.gov/icons/land/night/skc?size=medium',
        shortForecast: 'Clear',
        detailedForecast: 'Clear, with a low around 40.',
      },
      {
        number: 13,
        name: 'Friday',
        startTime: '2024-04-05T06:00:00-05:00',
        endTime: '2024-04-05T18:00:00-05:00',
        isDaytime: true,
        temperature: 72,
        temperatureUnit: 'F',
        temperatureTrend: null,
        probabilityOfPrecipitation: {
          unitCode: 'wmoUnit:percent',
          value: null,
        },
        dewpoint: {
          unitCode: 'wmoUnit:degC',
          value: 3.888888888888889,
        },
        relativeHumidity: {
          unitCode: 'wmoUnit:percent',
          value: 79,
        },
        windSpeed: '10 to 20 mph',
        windDirection: 'S',
        icon: 'https://api.weather.gov/icons/land/day/few?size=medium',
        shortForecast: 'Sunny',
        detailedForecast: 'Sunny, with a high near 72.',
      },
      {
        number: 14,
        name: 'Friday Night',
        startTime: '2024-04-05T18:00:00-05:00',
        endTime: '2024-04-06T06:00:00-05:00',
        isDaytime: false,
        temperature: 46,
        temperatureUnit: 'F',
        temperatureTrend: null,
        probabilityOfPrecipitation: {
          unitCode: 'wmoUnit:percent',
          value: null,
        },
        dewpoint: {
          unitCode: 'wmoUnit:degC',
          value: 3.3333333333333335,
        },
        relativeHumidity: {
          unitCode: 'wmoUnit:percent',
          value: 68,
        },
        windSpeed: '20 mph',
        windDirection: 'SE',
        icon: 'https://api.weather.gov/icons/land/night/few?size=medium',
        shortForecast: 'Mostly Clear',
        detailedForecast: 'Mostly clear, with a low around 46.',
      },
    ],
  },
};
